jobs:
  build-and-test:
    working_directory: ~/build-mosh
    macos:
      xcode: 9.4.0
    environment:
      LC_ALL: en_US.UTF-8
      LANG: en_US.UTF-8
    shell: /bin/bash --login -eo pipefail
    steps:
      - checkout
      - git submodule init
      - git submodule update
      - ./build-all.sh

workflows:
  version: 2
  build-test:
    jobs:
      - build-and-test
